spring:
  application:
    name: discovery-service
server:
  port: 8070

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8070/eureka
